import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../../compements/Navbar/navbar.module'
import Footer from '../../compements/Footer/footer.module'
import { CartProvider } from '../../context/cartContext'
import { BookProvider } from '../../context/bookContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BookProvider>
          <CartProvider>
            <Navbar></Navbar>
              {children}
            <Footer></Footer>
          </CartProvider>
        </BookProvider>
      </body>
    </html>
  )
}
